version: "3.9"

services:
  nextjs:
    build: .
    container_name: artulase-web
    working_dir: /app
    volumes:
      - ./artulase-website:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    tty: true
